#!/bin/bash

BASEDIR=`dirname $0`

# Load docker script environment variables
. $BASEDIR/env.sh

APPLICATION=$1
NODE_TYPE=$2
PORT=$3



CONTAINER_NAME=$APPLICATION'-'$PORT
DOCKER_IMAGE=$USER'/'$APPLICATION

EUREKA_SERVER_SERVICEURL=$4
SPRING_PROFILES_ACTIVE='SPRING_PROFILES_ACTIVE='$NODE_TYPE
ENV_EUREKA_INSTANCE='ENV_EUREKA_INSTANCE='$CONTAINER_NAME$DOCKER_DOMAIN

$BASEDIR/launch-container.sh $APPLICATION $PORT $EUREKA_SERVER_SERVICEURL -e $SPRING_PROFILES_ACTIVE -e $ENV_EUREKA_INSTANCE 
